force-app/main/default/objects/Case/fields/Case_Category__c.field-meta.xml
<CustomField>
    <fullName>Case_Category__c</fullName>
    <description>RUBX 1940: Support Request - Information request/advice on product functionality/operational guidance,   Defect - Confirmed/suspected software defect requiring correction</description>
    <inlineHelpText>Support Request - Information request/advice on product functionality/operational guidance,   Defect - Confirmed/suspected software defect requiring correction</inlineHelpText>
    <label>Case Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Support Request</fullName>
            </value>
            <value>
                <fullName>Defect</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Infrastructure</fullName>
            </value>
            <value>
                <fullName>Procedural BU</fullName>
            </value>
            <value>
                <fullName>Procedural Cust</fullName>
            </value>
            <value>
                <fullName>Procedural IT</fullName>
            </value>
            <value>
                <fullName>Outage</fullName>
                <isActive>false</isActive>
                <label>Outage</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test_CustomerCaseSynchTrigger.cls
@isTest
public class test_CustomerCaseSynchTrigger
{
	public static testmethod void doTest()
	{
		Case testParent = TestUtility.sampleCase();
		testParent.RecordTypeId = CustomerCaseSynchManager.ENGINEERING_LM_RECORD_TYPE;
		insert testParent;
		Case testChild = TestUtility.sampleIssueCase();
		testChild.ParentId = testParent.Id;
		insert testChild;
		
		testParent.Resolution_Type__c = CustomerCaseSynchManager.NOT_A_DEFECT_FIX_TYPE;
		update testParent;
		
		testChild = queryCase(testChild.Id);
		System.assertEquals(CustomerCaseSynchManager.SUPPORT_REQ_CASE_CAT , testChild.Case_Category__c);
		testParent = queryCase(testParent.Id);
		System.assertEquals(CustomerCaseSynchManager.SUPPORT_REQ_CASE_CAT , testParent.Case_Category__c);

		testParent.Resolution_Type__c = CustomerCaseSynchManager.ENHANCEMENT_FIX_TYPE;
		update testParent;

		testChild = queryCase(testChild.Id);
		System.assertEquals(CustomerCaseSynchManager.ENHANCEMENT_CASE_CAT , testChild.Case_Category__c);
		testParent = queryCase(testParent.Id);
		System.assertEquals(CustomerCaseSynchManager.ENHANCEMENT_CASE_CAT , testParent.Case_Category__c);
	}
	
	private static Case queryCase(Id caseId)
	{
		return [select Id, Case_Category__c from Case where Id = :caseId];
	}

}