force-app/main/default/objects/Billing_Schedule__c/Billing_Schedule__c.object-meta.xml
<CustomObject>
    <description>RUBX-1442 Billing schedule will define all billing terms and schedules</description>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{00000}</displayFormat>
        <label>Billing Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Schedule_Item__c/Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Rubx-1442 BIlling schedule Item related to billing schedule</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <label>Billing Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
 <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Schedule_Item__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <description>RUBX-1442 link records to billing schedule</description>
    <label>Billing Schedule</label>
    <referenceTo>Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Schedule_Item__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>RUBX-1442 Milestone percentage</description>
    <label>Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Billing_Terms__c.field-meta.xml
<CustomField>
    <fullName>License_Billing_Terms__c</fullName>
    <description>RUBX-1442 to store license billing terms</description>
    <label>License Billing Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Non Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RUBX-1441 need to attached billing schedule to quote line</description>
    <label>Billing Schedule</label>
    <referenceTo>Billing_Schedule__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/Standard_Billing_Schedule__mdt.object-meta.xml
<CustomObject>
    <description>RUBX-3685 used to store standard Billing schedules</description>
    <label>Standard Billing Schedule</label>
    <pluralLabel>Standard Billing Schedules</pluralLabel>
</CustomObject>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <description>RUBX-3685 billing milestone name</description>
    <label>Milestone Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>RUBX-3685 Percentage for each billing milestone</description>
    <label>Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/billingScheduleControllerTest.cls
/**
 * @File Name          : billingScheduleControllerTest.cls
 * @Description        :
 * @Author             : venu.navuluri@finastra.com
 * @Group              :
 * @Last Modified By   : venu.navuluri@finastra.com
 * @Last Modified On   : 05/02/2020, 12:46:55
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    1/27/2020   venu.navuluri@finastra.com     Initial Version
 **/
@isTest
private with sharing class billingScheduleControllerTest {
  private static final string ILF = 'ILF';
  private static final string FEILD_MISSING = 'Reguired Field missing';
  private static final string EXCEPTION_MESSAGE = 'Exception message triggered';
  private static final string Standard = 'Standard';
  private static final string BILLING_TERM = 'Billing Term - 1';

  /**
   * @description test data setup
   * @author Venu Navuluri | 27/01/2020
   * @return Quote
   **/
  private static SBQQ__Quote__c createQuote() {
    List<Opportunity> opps = TestDataFactory.CreateOpportunities(1, 200, true);
    SBQQ__Quote__c Quote = TestDataFactory.createSBQQuote(opps[0], false, true);
    return Quote;
  }
  /**
   * @description test method to return custom metadata records
   * @author Venu Navuluri | 27/01/2020
   * @return Quote
   **/
  private static testMethod void getILFStandardTermsTest() {
    test.startTest();
    List<Standard_Billing_Schedule__mdt> standardSchedules = [
      SELECT
        Id,
        DeveloperName,
        MasterLabel,
        Language,
        NamespacePrefix,
        Label,
        QualifiedApiName,
        Milestone_Name__c,
        Percentage__c
      FROM Standard_Billing_Schedule__mdt
    ];
    System.assertEquals(true, standardSchedules.size() > 0);
    billingScheduleController bs = new billingScheduleController();
    billingScheduleController.getILFStandardTerms(ILF);
    test.stoptest();
  }
  /**
   * @description test method to return billing schedule items for quote
   * @author Venu Navuluri | 27/01/2020
   * @return Quote
   **/
  private static testMethod void getExistingILFStandardTermsTest() {
    SBQQ__Quote__c Quote = createQuote();
    List<Billing_Schedule_Item__c> billingSchedules = new List<Billing_Schedule_Item__c>();
    Billing_Schedule__c bs = TestDataFactory.createBillingSchedule(
      true,
      Quote.Id,
      ILF
    );
    for (Integer count = 0; count < 50; count++) {
      billingSchedules.add(
        new Billing_Schedule_Item__c(
          Name = 'test' + count,
          Billing_Schedule__c = bs.id,
          Percentage__c = 100
        )
      );
    }
    insert billingSchedules;
    List<Billing_Schedule_Item__c> itemRecords;
    Test.startTest();
    itemRecords = billingScheduleController.getExistingILFStandardTerms(
      Quote.id
    );
    Test.StopTest();
    System.assertEquals(50, itemRecords.size());
  }
  /**
   * @description Positive test method to update Quote and Quote Lines
   * @author Venu Navuluri | 27/01/2020
   * @return Quote
   **/
  private static testMethod void updateQuote_QuoteLine_PositiveTest() {
    SBQQ__Quote__c Quote = createQuote();
    Billing_Schedule__c bs = TestDataFactory.createBillingSchedule(
      true,
      Quote.Id,
      ILF
    );

    Product2 prod = TestDataFactory.createProduct(ILF, true);
    List<SBQQ__QuoteLine__c> quoteLinesList = TestDataFactory.createSBQQuoteLines(
      10,
      Quote.Id,
      prod.Id,
      ILF,
      true
    );

    Test.startTest();
    billingScheduleController.updateQuote_QuoteLine(Quote.Id, bs.id, Standard);
    Test.StopTest();

    System.assertEquals(
      Standard,
      [
        SELECT Id, License_Billing_Terms__c
        FROM SBQQ__Quote__c
        WHERE Id = :Quote.Id
      ]
      .License_Billing_Terms__c
    );

    System.assertEquals(
      bs.id,
      [
        SELECT Id, Billing_Schedule__c
        FROM SBQQ__QuoteLine__c
        WHERE Id = :quoteLinesList[0].Id
      ]
      .Billing_Schedule__c
    );
  }
  /**
   * @description Negative test method to update Quote and Quote Lines
   * @author Venu Navuluri | 27/01/2020
   * @return Quote
   **/
  private static testMethod void updateQuote_QuoteLine_NegativeTest() {
    Test.startTest();
    try {
      billingScheduleController.updateQuote_QuoteLine(null, null, Standard);
    } catch (Exception ex) {
    }
    Test.StopTest();
  }
  /**
   * * @description: Unit test method for generateBillingScheduleItems method
   * @author venu.navuluri@finastra.com | 05/02/2020
   * @return testMethod
   **/
  private static testMethod void generateBillingScheduleItems_PositiveTest() {
    SBQQ__Quote__c Quote = createQuote();

    Product2 prod = TestDataFactory.createProduct(ILF, true);
    List<SBQQ__QuoteLine__c> quoteLinesList = TestDataFactory.createSBQQuoteLines(
      10,
      Quote.Id,
      prod.Id,
      ILF,
      true
    );

    CustomWrapper.InnerWrapper wrap1 = new CustomWrapper.InnerWrapper();
    wrap1.Name = Standard;
    wrap1.Percentage = 50;

    CustomWrapper.InnerWrapper wrap2 = new CustomWrapper.InnerWrapper();
    wrap2.Name = Standard;
    wrap2.Percentage = 50;

    List<CustomWrapper.InnerWrapper> itemList = new List<CustomWrapper.InnerWrapper>{
      wrap1,
      wrap2
    };
    CustomWrapper cw = new CustomWrapper();
    cw.itemList = itemList;

    string bSch;
    Test.startTest();
    bSch = billingScheduleController.generateBillingScheduleItems(
      cw,
      Quote.id,
      null,
      Standard
    );
    Test.StopTest();

    System.assertEquals(bSch, [SELECT id FROM Billing_Schedule__c LIMIT 1].Id);
  }

  /**
   * @description: Negative test method for generateBillingScheduleItems method
   * @author venu.navuluri@finastra.com | 05/02/2020
   * @return testMethod
   **/
  private static testMethod void generateBillingScheduleItems_NegativeTest1() {
    SBQQ__Quote__c Quote = createQuote();

    Product2 prod = TestDataFactory.createProduct(ILF, true);
    List<SBQQ__QuoteLine__c> quoteLinesList = TestDataFactory.createSBQQuoteLines(
      10,
      Quote.Id,
      prod.Id,
      ILF,
      true
    );
    CustomWrapper.InnerWrapper wrap1 = new CustomWrapper.InnerWrapper();
    wrap1.Name = Standard;
    wrap1.Percentage = 50;

    CustomWrapper.InnerWrapper wrap2 = new CustomWrapper.InnerWrapper();
    wrap2.Name = Standard;

    List<CustomWrapper.InnerWrapper> itemList = new List<CustomWrapper.InnerWrapper>{
      wrap1,
      wrap2
    };
    CustomWrapper cw = new CustomWrapper();
    cw.itemList = itemList;
    string bSch;
    Test.startTest();
    bSch = billingScheduleController.generateBillingScheduleItems(
      cw,
      Quote.id,
      null,
      Standard
    );
    Test.StopTest();
    System.assertEquals(0, [SELECT COUNT() FROM Billing_Schedule__c]);
  }
  /**
   * @description: Negative test method to cover test coverage
   * @author venu.navuluri@finastra.com | 05/02/2020
   * @return testMethod
   **/
  private static testMethod void generateBillingScheduleItems_NegativeTest2() {
    CustomWrapper.InnerWrapper wrap1 = new CustomWrapper.InnerWrapper();
    wrap1.Name = Standard;
    wrap1.Percentage = 50;

    CustomWrapper.InnerWrapper wrap2 = new CustomWrapper.InnerWrapper();
    wrap2.Name = Standard;

    List<CustomWrapper.InnerWrapper> itemList = new List<CustomWrapper.InnerWrapper>{
      wrap1,
      wrap2
    };
    CustomWrapper cw = new CustomWrapper();
    cw.itemList = itemList;
    string bSch;
    Test.startTest();
    bSch = billingScheduleController.generateBillingScheduleItems(
      cw,
      null,
      null,
      Standard
    );
    Test.StopTest();
    System.assertEquals(0, [SELECT COUNT() FROM Billing_Schedule__c]);
  }
}