force-app/main/default/objects/Billing_Schedule__c/Billing_Schedule__c.object-meta.xml
<CustomObject>
    <description>RUBX-1442 Billing schedule will define all billing terms and schedules</description>
    <label>Billing Schedule</label>
    <nameField>
        <displayFormat>BS-{00000}</displayFormat>
        <label>Billing Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Schedule__c/fields/Billing_Term__c.field-meta.xml
<CustomField>
    <fullName>Billing_Term__c</fullName>
    <label>Billing Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Term - 1</fullName>
            </value>
            <value>
                <fullName>Billing Term - 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Schedule__c/fields/ProdType__c.field-meta.xml
<CustomField>
    <fullName>ProdType__c</fullName>
    <description>RUBX-1441 Add prod type to billing schedule</description>
    <label>ProdType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Schedule__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Billing Schedules</relationshipLabel>
    <relationshipName>Billing_Schedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Schedule_Item__c/Billing_Schedule_Item__c.object-meta.xml
<CustomObject>
    <description>Rubx-1442 BIlling schedule Item related to billing schedule</description>
    <label>Billing Schedule Item</label>
    <nameField>
        <label>Billing Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Schedule Items</pluralLabel>
 <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Schedule_Item__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <description>RUBX-1442 link records to billing schedule</description>
    <label>Billing Schedule</label>
    <referenceTo>Billing_Schedule__c</referenceTo>
    <relationshipLabel>Billing Schedule Items</relationshipLabel>
    <relationshipName>Billing_Schedule_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Schedule_Item__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>RUBX-1442 Milestone percentage</description>
    <label>Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/License_Billing_Terms__c.field-meta.xml
<CustomField>
    <fullName>License_Billing_Terms__c</fullName>
    <description>RUBX-1442 to store license billing terms</description>
    <label>License Billing Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Non Standard</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Billing_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Billing_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RUBX-1441 need to attached billing schedule to quote line</description>
    <label>Billing Schedule</label>
    <referenceTo>Billing_Schedule__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/ProdType__c.field-meta.xml
<CustomField>
        <fullName>ProdType__c</fullName>
        <label>ProdType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ProdType</valueSetName>
        </valueSet>
    </CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/Standard_Billing_Schedule__mdt.object-meta.xml
<CustomObject>
    <description>RUBX-3685 used to store standard Billing schedules</description>
    <label>Standard Billing Schedule</label>
    <pluralLabel>Standard Billing Schedules</pluralLabel>
</CustomObject>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/fields/Billing_Term__c.field-meta.xml
<CustomField>
    <fullName>Billing_Term__c</fullName>
    <label>Billing Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Term - 1</fullName>
                <default>true</default>
                <label>Billing Term - 1</label>
            </value>
            <value>
                <fullName>Billing Term - 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <description>RUBX-3685 billing milestone name</description>
    <label>Milestone Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <description>RUBX-3685 Percentage for each billing milestone</description>
    <label>Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Standard_Billing_Schedule__mdt/fields/ProdType__c.field-meta.xml
<CustomField>
    <fullName>ProdType__c</fullName>
    <description>RUBX-3685 ProdType for standard billing schedule</description>
    <label>ProdType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILF</fullName>
                <default>true</default>
                <label>ILF</label>
            </value>
            <value>
                <fullName>RLF</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ProdType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ILF</fullName>
    </customValue>
    <customValue>
        <fullName>RLF</fullName>
    </customValue>
    <customValue>
        <fullName>ILSS</fullName>
    </customValue>
    <customValue>
        <fullName>ILHS</fullName>
    </customValue>
    <customValue>
        <fullName>ILHM</fullName>
    </customValue>
    <customValue>
        <fullName>ILHF</fullName>
    </customValue>
    <customValue>
        <fullName>SVPT</fullName>
    </customValue>
    <customValue>
        <fullName>SVTT</fullName>
    </customValue>
    <customValue>
        <fullName>TRAN</fullName>
    </customValue>
    <customValue>
        <fullName>HWR</fullName>
    </customValue>
    <customValue>
        <fullName>ILSF</fullName>
    </customValue>
    <customValue>
        <fullName>DVC1</fullName>
    </customValue>
    <customValue>
        <fullName>DVC2</fullName>
    </customValue>
    <customValue>
        <fullName>DVCS</fullName>
    </customValue>
    <customValue>
        <fullName>RLFF</fullName>
    </customValue>
    <customValue>
        <fullName>HOSS</fullName>
    </customValue>
    <masterLabel>ProdType</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/billingScheduleController.cls
/**
 * @File Name          : billingScheduleController.cls
 * @Description        :
 * @Author             : venu.navuluri@finastra.com
 * @Group              :
 * @Last Modified By   : venu.navuluri@finastra.com
 * @Last Modified On   : 06/02/2020, 12:24:25
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    09/12/2019   venu.navuluri@finastra.com     Initial Version
 **/
public with sharing class billingScheduleController {
  private static final String SEARCH_TERM = '%' + Constants.ILF + '%';

  /**
   * @description RUBX-3681 generating billing schedule record and child records, then update quote and ILF quotelines.
   * @author venu.navuluri@finastra.com | 2/4/2020
   * @param wrapper
   * @param quoteId
   * @param billingTerm
   * @param selectedLicenseSchedule
   * @return String
   **/
  @AuraEnabled
  public static String generateBillingScheduleItems(
    CustomWrapper wrapper,
    String quoteId,
    String billingTerm,
    String selectedLicenseSchedule
  ) {
    String result, eMsg;
    Boolean isBillingScheduleCreated = false;
    Boolean isBillingScheduleItemsCreated = false;
    savepoint sp = Database.setSavepoint();
    Billing_Schedule__c obs = new Billing_Schedule__c(
      ProdType__c = Constants.ILF,
      Quote__c = quoteId
    );
    try {
      insert obs;
      isBillingScheduleCreated = true;
      result = obs.Id;
    } catch (Exception ex) {
      eMsg =
        'Error at line # ' +
        ex.getLineNumber() +
        ' cause => ' +
        ex.getMessage() +
        ' class name ' +
        ex.getStackTraceString();
      Database.rollback(sp);
      return eMsg;
    }

    if (isBillingScheduleCreated) {
      List<Billing_Schedule_Item__c> newItems = new List<Billing_Schedule_Item__c>();

      for (Integer i = 0; i < Wrapper.itemList.size(); i++) {
        Billing_Schedule_Item__c bsItem = new Billing_Schedule_Item__c(
          Billing_Schedule__c = obs.id,
          Name = Wrapper.itemList[i].Name,
          Percentage__c = Wrapper.itemList[i].Percentage
        );
        newItems.add(bsItem);
      }

      if (!newItems.isEmpty()) {
        try {
          insert newItems;
          isBillingScheduleItemsCreated = true;
        } catch (Exception ex) {
          eMsg =
            'Error at line # ' +
            ex.getLineNumber() +
            ' cause => ' +
            ex.getMessage() +
            ' class name ' +
            ex.getStackTraceString();
          Database.rollback(sp);
          return eMsg;
        }
      }
    }

    if (isBillingScheduleItemsCreated) {
      try {
        updateQuote_QuoteLine(quoteId, obs.id, selectedLicenseSchedule);
      } catch (Exception ex) {
        eMsg =
          'Error at line # ' +
          ex.getLineNumber() +
          ' cause => ' +
          ex.getMessage() +
          ' class name ' +
          ex.getStackTraceString();
        Database.rollback(sp);
        return eMsg;
      }
    }
    return result;
  }

  /**
   * @description RUBX-3681 returns standard custom metadata
   * @author Venu Navuluri | 25/01/2020
   * @param billingTerm
   * @return List<Standard_Billing_Schedule__mdt>
   **/
  @AuraEnabled(cacheable=true)
  public static List<Standard_Billing_Schedule__mdt> getILFStandardTerms(
    String billingTerm
  ) {
    return [
      SELECT Milestone_Name__c, Percentage__c
      FROM Standard_Billing_Schedule__mdt
      WHERE Billing_Term__c = :billingTerm AND ProdType__c = :Constants.ILF
    ];
  }
  /**
   * @description RUBX-3681 returns existing billing schedule items
   * @author Venu Navuluri | 25/01/2020
   * @param quoteId
   * @return List<Billing_Schedule_Item__c>
   **/
  @AuraEnabled(cacheable=true)
  public static List<Billing_Schedule_Item__c> getExistingILFStandardTerms(
    Id quoteId
  ) {
    return [
      SELECT Name, Percentage__c
      FROM Billing_Schedule_Item__c
      WHERE
        Billing_Schedule__r.Quote__c = :quoteId
        AND Billing_Schedule__r.ProdType__c = :Constants.ILF
    ];
  }
  /**
   * @description RUBX-3681 updated Quote and assign billing schedule id to all related quote lines
   * @author Venu Navuluri | 25/01/2020
   * @param quoteId, bsId
   * @return void
   **/
  @AuraEnabled
  public static void updateQuote_QuoteLine(
    Id quoteId,
    Id bsId,
    String selectedLicenseSchedule
  ) {
    //selectedLicenseSchedule
    SBQQ__Quote__c uQuote = new SBQQ__Quote__c(
      Id = quoteId,
      License_Billing_Terms__c = selectedLicenseSchedule
    );

    try {
      update uQuote;
    } catch (Exception e) {
      AuraHandledException auraException = new AuraHandledException(
        e.getMessage()
      );
      auraException.setMessage(e.getMessage());
      throw auraException;
    }
    SBQQ__QuoteLine__c[] qLine_list = [
      SELECT Id, ProdType__c, Billing_Schedule__c
      FROM SBQQ__QuoteLine__c
      WHERE SBQQ__quote__c = :quoteId AND ProdType__c LIKE :SEARCH_TERM
      FOR UPDATE
    ];
    List<SBQQ__QuoteLine__c> updatedList = new List<SBQQ__QuoteLine__c>();
    for (SBQQ__QuoteLine__c ql : qLine_list) {
      updatedList.add(
        new SBQQ__QuoteLine__c(Id = ql.Id, Billing_Schedule__c = bsId)
      );
    }
    if (updatedList.size() > 0) {
      try {
        update updatedList;
      } catch (Exception e) {
        throw new AuraHandledException(e.getMessage());
      }
    }
  }
}