force-app/main/default/objects/Contract/fields/Apply_Standard_CPI__c.field-meta.xml
<CustomField>
        <fullName>Apply_Standard_CPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Apply Standard CPI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Contract/fields/CPI__c.field-meta.xml
<CustomField>
        <fullName>CPI__c</fullName>
        <label>CPI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US CPI-U</fullName>
                </value>
                <value>
                    <fullName>US CPI-U G&amp;S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Contract/fields/CPI_Index_Type__c.field-meta.xml
<CustomField>
        <fullName>CPI_Index_Type__c</fullName>
        <label>CPI Index Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CAP</fullName>
                </value>
                <value>
                    <fullName>FIX</fullName>
                </value>
                <value>
                    <fullName>No Increase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/Contract/fields/Maximum_Rate__c.field-meta.xml
<CustomField>
        <fullName>Maximum_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Maximum Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </CustomField>

force-app/main/default/objects/Contract/fields/Minimum_Rate__c.field-meta.xml
<CustomField>
        <fullName>Minimum_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Minimum Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </CustomField>

force-app/main/default/objects/Contract/fields/No_CPI__c.field-meta.xml
<CustomField>
        <fullName>No_CPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No CPI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/Contract/fields/Use_Existing_CPI__c.field-meta.xml
<CustomField>
        <fullName>Use_Existing_CPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Existing CPI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Additional_Increase__c.field-meta.xml
<CustomField>
        <fullName>Additional_Increase__c</fullName>
        <inlineHelpText>Please enter amount in % e.g. 5% if you would like the increase is local CPI +5%. Any value less than 3% here will trigger approval rule</inlineHelpText>
        <label>Additional % Increase</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Apply_Standard_CPI__c.field-meta.xml
<CustomField>
        <fullName>Apply_Standard_CPI__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Apply Standard CPI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/CPI__c.field-meta.xml
<CustomField>
        <fullName>CPI__c</fullName>
        <inlineHelpText>Please select the local CPI that should apply</inlineHelpText>
        <label>CPI</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US CPI-U</fullName>
                </value>
                <value>
                    <fullName>US CPI-U G&amp;S</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/CPI_Index_Type__c.field-meta.xml
<CustomField>
    <fullName>CPI_Index_Type__c</fullName>
    <inlineHelpText>No Increase: No CPI increase should apply
CAP: Finastra Standard rate should apply but apply specified CPI as CAP
FIX: Specified CPI should apply
None: CPI increase is a fixed rate e.g. 5%. (indicate 5% as min and max below).</inlineHelpText>
    <label>CPI Index Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>FIX</fullName>
            </value>
            <value>
                <fullName>No Increase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Maximum_Rate__c.field-meta.xml
<CustomField>
        <fullName>Maximum_Rate__c</fullName>
        <inlineHelpText>Use this when there&apos;s max increase should apply or we are applying fix increase rate - any value appear here will trigger approval rules</inlineHelpText>
        <label>Maximum Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Minimum_Rate__c.field-meta.xml
<CustomField>
        <fullName>Minimum_Rate__c</fullName>
        <inlineHelpText>Use this when there&apos;s minimum increase should apply or we are applying fix increase rate</inlineHelpText>
        <label>Minimum Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/No_CPI__c.field-meta.xml
<CustomField>
        <fullName>No_CPI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No CPI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Standard_Index__c.field-meta.xml
<CustomField>
        <fullName>Standard_Index__c</fullName>
        <inlineHelpText>Always select Standard Rate. This is Finastra Standard Rate and it will apply when CPI Index Type = CAP is selected. Otherwise, this value will be ignored</inlineHelpText>
        <label>Standard Index</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard Rate</fullName>
                    <default>true</default>
                    <label>Standard Rate</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Use_Existing_CPI__c.field-meta.xml
<CustomField>
        <fullName>Use_Existing_CPI__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checkbox to indicate that the deal is at the same rate as the framework/master agreement.</inlineHelpText>
        <label>Use Existing CPI</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/classes/ContractTriggerHandler.cls
/**
 * Handler class for the OpportunityTrigger
 */

public with sharing class ContractTriggerHandler extends TriggerHandler {

    protected override void beforeInsert() {
        System.debug('Before Insert ContractTriggerHandler Begins');
        
        Set<Id> opportunityIds = new Set<Id>();
        for (Contract c : (List<Contract>) Trigger.new) {
            if (c.SBQQ__Opportunity__c != null) {
            	opportunityIds.add(c.SBQQ__Opportunity__c);
            }
        }
        
        Map<Id, Id> oppIdQuoteIdMap = new Map<Id, Id>();
        if (opportunityIds != null && opportunityIds.size() > 0) {
            for (Opportunity opp : [select Id, SBQQ__PrimaryQuote__c from Opportunity where Id in :opportunityIds]) {
                if (opp.SBQQ__PrimaryQuote__c != null) {
                    oppIdQuoteIdMap.put(opp.Id, opp.SBQQ__PrimaryQuote__c);
                }
            }
        }
		
        Map<Id, SBQQ__Quote__c> quoteIdQuoteMap = new Map<Id, SBQQ__Quote__c>();
        if (oppIdQuoteIdMap.values().size() > 0) {
        	for (SBQQ__Quote__c quote : [select Id, Standard_Index__c, Additional_Increase__c, CPI__c, CPI_Index_Type__c, Maximum_Rate__c, Minimum_Rate__c, No_CPI__c, Use_Existing_CPI__c, Apply_Standard_CPI__c from SBQQ__Quote__c where Id in :oppIdQuoteIdMap.values()]) {
                quoteIdQuoteMap.put(quote.id, quote);
            }    
        }
        
		//Populate the CPI fields from the primary quote.
        for (Contract c : (List<Contract>) Trigger.new) {
            if (c.SBQQ__Opportunity__c != null) {
                if (oppIdQuoteIdMap.containsKey(c.SBQQ__Opportunity__c)) {
                    Id quoteId = oppIdQuoteIdMap.get(c.SBQQ__Opportunity__c);
                    if (quoteIdQuoteMap.containsKey(quoteId)) {
                        SBQQ__Quote__c dataQuote = quoteIdQuoteMap.Get(quoteId);
                         if (String.isBlank(dataQuote.Standard_Index__c) == false) {
                            c.Standard_Index__c = dataQuote.Standard_Index__c;
                        }
                   
                        if (String.isBlank(dataQuote.CPI__c) == false) {
                            c.CPI__c = dataQuote.CPI__c;
                        }
                        if (String.isBlank(dataQuote.CPI_Index_Type__c) == false) {
                            c.CPI_Index_Type__c = dataQuote.CPI_Index_Type__c;
                        }
                        //These 3 fields can now be blank, the default value was removed.
                        c.Additional_Increase__c = dataQuote.Additional_Increase__c;
                        c.Maximum_Rate__c  = dataQuote.Maximum_Rate__c ;
                        c.Minimum_Rate__c  = dataQuote.Minimum_Rate__c ;
                        
                        c.No_CPI__c = dataQuote.No_CPI__c;
                        c.Use_Existing_CPI__c = dataQuote.Use_Existing_CPI__c;
                        c.Apply_Standard_CPI__c = dataQuote.Apply_Standard_CPI__c;
                    }
                }
            }
        }
        System.debug('Before Insert ContractTriggerHandler finished');
    }
}