force-app/main/default/objects/Asset/fields/Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Review_Date__c</fullName>
    <description>RUBX-77: Review date for LCA (License Compliance Audit)</description>
    <inlineHelpText>Review date for LCA</inlineHelpText>
    <label>Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Compliance_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Sub_Status__c</fullName>
    <description>RUBX-1018: Compliance Sub status - values will be added in RUBX-1019</description>
    <label>Compliance Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>1st Follow-up</fullName>
            </value>
            <value>
                <fullName>2nd Follow-up</fullName>
            </value>
            <value>
                <fullName>3rd Follow-up</fullName>
            </value>
            <value>
                <fullName>4th Follow-up</fullName>
            </value>
            <value>
                <fullName>L2 - Audit Tool Assistance</fullName>
            </value>
            <value>
                <fullName>On Hold Pending AM</fullName>
            </value>
            <value>
                <fullName>On Hold Pending Audit Contact</fullName>
            </value>
            <value>
                <fullName>On Hold Pending Reports From Other Sites</fullName>
            </value>
            <value>
                <fullName>Pending Complete / Accurate Report</fullName>
            </value>
            <value>
                <fullName>Analysis submitted for QA</fullName>
            </value>
            <value>
                <fullName>QA Complete</fullName>
            </value>
            <value>
                <fullName>Referred to CommOps</fullName>
            </value>
            <value>
                <fullName>Referred to Licence Principal</fullName>
            </value>
            <value>
                <fullName>Re-audit, Referred to Licence Principal</fullName>
            </value>
            <value>
                <fullName>Referred to ProdMgt/Dev/LicDel</fullName>
            </value>
            <value>
                <fullName>Audit Holiday</fullName>
            </value>
            <value>
                <fullName>Audit Tools Issue</fullName>
            </value>
            <value>
                <fullName>Custom License/no VBP matrix</fullName>
            </value>
            <value>
                <fullName>Duplicate Account/LC</fullName>
            </value>
            <value>
                <fullName>GHO/Hub/Billing site</fullName>
            </value>
            <value>
                <fullName>Implementation/Support Issue</fullName>
            </value>
            <value>
                <fullName>Legal Sanctions/Political Situation</fullName>
            </value>
            <value>
                <fullName>New Customer/Product -  Less Than 1 Yr Data</fullName>
            </value>
            <value>
                <fullName>No Audit Report Received</fullName>
            </value>
            <value>
                <fullName>No Auditable Product</fullName>
            </value>
            <value>
                <fullName>Licensed - Product Not In Use</fullName>
            </value>
            <value>
                <fullName>Licensed - Not Implemented</fullName>
            </value>
            <value>
                <fullName>New customer/product, still under implementation</fullName>
            </value>
            <value>
                <fullName>Ongoing sales negotiations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/LCA_Account__c.field-meta.xml
<CustomField>
    <fullName>LCA_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RUBX-1924 New account lookup field to display LCA cases in separate related list on Account layout</description>
    <label>LCA Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LCA Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/**
* @File Name          : CaseTriggerHandler.cls
* @Description        : Case Trigger Handler
* @Author             : Peter Sabry
* @Group              : 
* @Last Modified By   : Venu Navuluri
* @Last Modified On   : 1/10/2020, 10:59:40 AM
* @Modification Log   : 
* Ver       Date            Author      		    Modification
* 1.0    04/11/2019   Peter Sabry     Initial Version
**/
public with sharing class CaseTriggerHandler extends TriggerHandler {
    
    protected override void beforeInsert() {}
    
    protected override void afterInsert() {}
    
    protected override void beforeUpdate() {}
    
    protected override void afterUpdate() {
        List<Case> cases = (List<Case>) Trigger.new;
        Map<Id, Case> oldMap = (Map<Id, Case>) Trigger.oldMap;
        
        //Set Asset Review date to case close date + 1 year when LCA case status is changed to closed
        setAssetNextReviewDate(cases, oldMap);
        
        //trigger approval process for awaiting deselection approval
        submitApprovalforLCADeselection(cases, oldMap);
        
        //notified when an audit outcome is compliant
        notifySalesWhenCompliant(cases, oldMap);
    }
    
    protected override void beforeDelete() {}
    
    protected override void afterDelete() {}
    
    protected override void afterUndelete() {}
    
    /**
* @description After the completion of the review, the asset review date is re-calculated using the Case close date.
* @author Peter Sabry | 08/11/2019 
* @param newList 
* @param oldMap 
* @return void 
**/
    private void setAssetNextReviewDate(List<Case> newList, Map<Id, Case> oldMap) {
        Map<String, Id> recordTypesMap = CommonUtils.getRecordTypesByObjectName('Case');            
        Map<Id, Date> assetCaseCloseDateMap = new Map<Id, Date>();
        for(Case assetCase : newList) {
            if(assetCase.RecordTypeId == recordTypesMap.get(Constants.CASE_LCA_RECORD_TYPE_DEV_NAME) && oldMap.get(assetCase.Id).Status != assetCase.Status && (assetCase.Status == Constants.CASE_STATUS_CLOSED || assetCase.Status == Constants.CASE_STATUS_AUDITED || assetCase.Status == Constants.CASE_STATUS_NOT_AUDITED)) {
                assetCaseCloseDateMap.put(assetCase.AssetId, assetCase.ClosedDate.date());
            }
        }
        List<Asset> assetsToUpdate = new List<Asset>([Select Id, Review_Date__c from Asset where Id in :assetCaseCloseDateMap.keyset()]);
        for(Asset asset : assetsToUpdate) {
            asset.Review_Date__c = CommonUtils.getNextFinancialYearQuarterStartDate(assetCaseCloseDateMap.get(asset.Id)).date();
        }
        if(assetsToUpdate.size() > 0) {
            database.update(assetsToUpdate);
        }
    }
    /**
* @description RUBX-82 The ability to trigger approve process when status set to ( =Awaiting Deselection Approval)
* @author Venu Navuluri | 11/11/2019 
* @param newList 
* @param oldMap 
* @return void 
**/
    
    private void submitApprovalforLCADeselection(List<Case> newList, Map<Id, Case> oldMap) {
        
        //Request for all Cases 
        
        Approval.ProcessSubmitRequest [] requestList = new Approval.ProcessSubmitRequest []{};
            Map<String, Id> recordTypesMap = CommonUtils.getRecordTypesByObjectName('Case');    
        Approval.ProcessResult[] processResults = null;
        
        for(Case assetCase : newList) {             
            if(assetCase.status != oldMap.get(assetCase.Id).status && assetCase.status == Constants.CASE_STATUS_DESELECTION_APPROVAL && assetCase.RecordTypeId == recordTypesMap.get(Constants.CASE_LCA_RECORD_TYPE_DEV_NAME) ){
                
                // Create an approval request for the case
                Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
                req.setComments('Submitting LCA Desection for approval.');
                req.setObjectId(assetCase.id);
                req.setProcessDefinitionNameOrId('LCA_Deselection_Approval');
                requestList.add(req);
            }
            if(!requestList.isEmpty())
                processResults = Approval.process(requestList, false);
        }
    }
 /**
* @description RUBX-1166 - Sales and License Principle to be notified when an audit outcome is compliant
* @author Venu Navuluri| 14/11/2019 
* @param newList 
* @param oldMap 
* @return void 
**/   
    private void notifySalesWhenCompliant(List<Case> newList, Map<Id, Case> oldMap) {
        
        Set<Id> accountIds = new Set<Id>();
        String chatterPost = System.Label.LCA_Notify_Sales_When_Compliant;
        ID groupId = CommonUtils.getChatterGroupId(Constants.LICENSE_PRINCIPLE_TEAM);
        
        for(Case assetCase : newList) { 
            if(assetCase.Compliance_Sub_Status__c  != oldMap.get(assetCase.Id).Compliance_Sub_Status__c 
               && assetCase.status == Constants.CASE_STATUS_AUDITED && assetCase.Compliance_Sub_Status__c == Constants.COMPLIANCE_SUB_STATUS_COMPLIANT){
                   accountIds.add(assetCase.LCA_Account__c);
               }
        }
        Map<Id,Account> accountMap = new Map<Id, Account>([select Id, OwnerId from Account where Id IN :accountIds]);
        
        for(Case assetCase : newList) { 
            if(assetCase.Compliance_Sub_Status__c  != oldMap.get(assetCase.Id).Compliance_Sub_Status__c 
               && assetCase.status == Constants.CASE_STATUS_AUDITED && assetCase.Compliance_Sub_Status__c == Constants.COMPLIANCE_SUB_STATUS_COMPLIANT){
                   
                    ConnectApiHelper.postFeedItemWithMentions(
                       Network.getNetworkId(), //community Id where to post, or "internal", or null
                       assetCase.id, //this is the record where the post will appear
                       '{' + accountMap.get(assetCase.LCA_Account__c).OwnerId + '}'+' '+ '{' + groupId + '}' +' '+ chatterPost +' ' +'{' + assetCase.OwnerId + '}' );
                   
               }
        }
    }
    
    
}