force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>RUBX-1560 : This field is used to capture Sales Region</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type is used for Customers(converted through Prospects)</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>RUBX-512 : Field to capture Region</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Americas</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>MEA</fullName>
    </customValue>
    <customValue>
        <fullName>NACM</fullName>
    </customValue>
    <description>RUBX-1560 : List of all Sales Regions</description>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/test_CommunityProfile.cls
@isTest
public class test_CommunityProfile
{
	private static Map<String,RecordType> getRecordTypeId() {
		// Create test data (a new Account and contact)
		Map<String,RecordType> recordTypesByName = new Map<String,RecordType>();
		for (List<RecordType> recordTypes :  [SELECT Id, Name FROM RecordType]){
			for (RecordType recordType : recordTypes){
				recordTypesByName.put(recordType.Name, recordType);
			}
		}
		return recordTypesByName;
	}
	private static Account getAccount() {
		Map<String,RecordType> recordTypesByName = getRecordTypeId();
		Account acct = new Account();
		acct.Name = 'Test Account';
		acct.recordTypeId = recordTypesByName.get('Finastra Customer').Id;
		acct.Region__c = 'Europe';
		acct.site = 'test site';
		acct.type = 'Customer';
		acct.Country__c = 'United Kingdom';
		insert acct;

		return acct;
	}

	private static contact getContact(Account acct) {
		Map<String,RecordType> recordTypesByName = getRecordTypeId();
		Contact con = New Contact();
		con.Lastname = 'Testing';
		con.RecordTypeId = recordTypesByName.get('Customer Portal').Id;
		con.AccountId = acct.Id;
		con.email = 'community@test.com';
		insert con;
		return con;
	}

	private static User getUser(Contact con) {
		//Profile p = [select Id from Profile where UserType = 'Standard' LIMIT 1];
		Profile standardProf = [select id from profile where name='Customer Community Banking User'];
		User su = new User(alias = 'comm', email='community@test.com',
				emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
				localesidkey='en_US', profileid = standardProf.Id,
				timezonesidkey='Europe/London', username='community@test.com', contactId=con.Id);

		insert su;
		return su;
	}


/*
	static void testChatterFeed()
	{
 		User u = TestUtils.getStandardInternalUser('testUT_1');
    	insert u;



		FeedItem post2 = new FeedItem();
		post2.ParentId = u.Id; //eg. Opportunity id, custom object id..
		post2.Body = 'Enter post text here';
		post2.LinkUrl = 'http://www.someurl.com';
		insert post2;

		//Adding a Content post
		FeedItem post3 = new FeedItem();
		post3.ParentId = su.ID; //eg. Opportunity id, custom object id..
		post3.Body = 'Enter post text here';
		post3.ContentFileName = 'sample.pdf';
		insert post3;


		Account acct = getAccount();
	    Contact con = getContact(acct);
	    User su = getUser(con);
	    insert su;

	    Test.startTest();
		System.runAs(su) {

	        //Case cs = TestUtils.getCase(acct, con);
	        //insert cs;

		    Troubleshooting__kav a = new Troubleshooting__kav(
	            Title = 'test apex',
	            Summary = 'test from apex',
	            URLName = 'test'
	        );
	        insert a;
	        system.debug('parent Id: ' + a.knowledgeArticleId);

	        FeedItem post = new FeedItem();
			post.ParentId = a.Id;
			post.Body = 'Enter post text here';
			insert post;

			EntitySubscription follow = new EntitySubscription (
	        parentId = a.id,
	        subscriberid = su.Id);
			insert follow;



			PageReference testPR = Page.community_ChatterFeed;
			Test.setCurrentPage(testPR);
			community_ChatterFeedController controller = New community_ChatterFeedController();

		}

		Test.stopTest();
	}
	*/

	@isTest
	static void testPreferences() {

		Account acct = getAccount();
		Contact con = getContact(acct);
		User su = getUser(con);

		Test.startTest();
		system.runAs(su) {
			PageReference testPR = Page.community_CustomerPreferences;
			Test.setCurrentPage(testPR);
			System.debug('contact: ' + su.contactId);
			community_PreferenceController controller = New community_PreferenceController();
			controller.cancel();
			controller.getIsEdit();
			controller.save();
		}

		Test.stopTest();

	}

	@isTest
	static void testHomePage() {
/*
		Account acct = getAccount();
        Contact con = getContact(acct);
        User su = getUser(con);
        //con.OwnerId = su.Id;
        //update con;
        //acct.OwnerId = su.Id;
       // update acct;
		Test.startTest();
		system.runAs(su) {
			PageReference testPR = Page.community_MI_Home;
			Test.setCurrentPage(testPR);
			System.debug('contact: ' + su.contactId);
			community_MI_HomeController controller = New community_MI_HomeController();

		}

		Test.stopTest();
*/
	}


	@isTest
	static void testAdvocate() {

		Test.startTest();
		PageReference testPR = Page.community_CustomerAdvocate;
		Test.setCurrentPage(testPR);
		community_AdvocateController controller = New community_AdvocateController();
		Test.stopTest();

	}

}