force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>RUBX-1560 : This field is used to capture Sales Region</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This record type is used for Customers(converted through Prospects)</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>United Kingdom</fullName>
    </customValue>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Americas</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pacific</fullName>
    </customValue>
    <customValue>
        <fullName>Europe</fullName>
    </customValue>
    <customValue>
        <fullName>MEA</fullName>
    </customValue>
    <customValue>
        <fullName>NACM</fullName>
    </customValue>
    <description>RUBX-1560 : List of all Sales Regions</description>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/test_CommunityPremiumService.cls
@isTest
private class test_CommunityPremiumService {

        @isTest static void testBehaviour() {
                // Implement test code
                Map<String,RecordType> recordTypesByName = new Map<String,RecordType>();
                for (List<RecordType> recordTypes :  [SELECT Id, Name FROM RecordType]){
                        for (RecordType recordType : recordTypes){
                                recordTypesByName.put(recordType.Name, recordType);
                        }
                }
                Account acct = new Account();
                acct.Name = 'Test Account';
                acct.recordTypeId = recordTypesByName.get('Finastra Customer').Id;
                acct.Region__c = 'Europe';
                acct.site = 'test site';
                acct.type = 'Customer';
                acct.Country__c = 'United Kingdom';
                insert acct;

                Contact con = New Contact();
                con.Lastname = 'Testing';
                con.RecordTypeId = recordTypesByName.get('Customer Portal').Id;
                con.AccountId = acct.Id;
                con.email = 'community@test.com';
                insert con;

                Profile standardProf = [select id from profile where name='Customer Community BANKING User'];
                User su = new User(alias = 'comm', email='community@test.com',
                        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                        localesidkey='en_US', profileid = standardProf.Id,
                        timezonesidkey='Europe/London', username='community@test.com', contactId=con.Id);
                insert su;

                Case csPremium = TestUtils.getCase(acct, con);
                csPremium.recordtypeId = recordTypesByName.get('Premium Support Services').Id;
                //csPremium.ownerId = u.Id;
                insert csPremium;

                Test.startTest();
                System.runAs(su) {
                        pageReference pageDetailsPremium = Page.community_CaseDetails;
                        ApexPages.StandardController scPremium = new ApexPages.standardController(csPremium);
                        Community_CaseViewExtension conDetailsPremium = New Community_CaseViewExtension(scPremium);


                }
                Test.stopTest();
        }



}