force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Bill_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Billing Address for Account</description>
    <label>Primary Bill-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account.</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Bill-To)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Ship_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Shipping Address for Account</description>
    <label>Primary Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Ship-To)</relationshipLabel>
    <relationshipName>Shipping_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>RUBX-1672: This object will be used to maintain various addresses related to an account</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : This field is used to associate an Account with Address Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>RUBX-1672 : This field is used to capture City of the address</description>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-1672 : This field is used to capture Country for Address</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>RUBX-1672 : This field is used to capture State or Province name for the address</description>
    <label>State/Province</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>RUBX-1672 : This field is used to capture Postal Code for the address</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerHandler_Test.cls
/**
 * @File Name          : AccountTriggerHandler_Test.cls
 * @Description        : Test class for all Account Trigger Handler methods
 * @Author             : Aakanksha Sharma
 * @Group              :
 * @Last Modified By   : Aakanksha Sharma
 * @Last Modified On   : 28/01/2020, 18:21:50
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    28/01/2020   Aakanksha Sharma     Initial Version
 **/
@istest
public with sharing class AccountTriggerHandler_Test {
  /**
   * @description Method to test if OOTB address fields are updated based on Address lookup fields on Account
   * @author Aakanksha Sharma | 28/01/2020
   * @return testMethod
   **/
  public static testMethod void updateAddressFields_PositiveSingleTest() {
    Account acc = TestDataFactory.createAccounts(1, true)[0];
    Address__c addr = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    // Perform test
    Test.startTest();
    acc.Primary_Bill_To__c = addr.id;
    acc.Primary_Ship_To__c = addr.id;
    update acc;
    Test.stopTest();

    List<Account> insertedAcc = new List<Account>(
      [
        SELECT
          id,
          BillingCity,
          BillingState,
          BillingPostalCode,
          BillingCountry,
          ShippingCity,
          ShippingState,
          ShippingPostalCode,
          ShippingCountry
        FROM Account
        WHERE id = :acc.id
      ]
    );

    System.assertEquals(insertedAcc[0].BillingCity, addr.City__c);
    System.assertEquals(insertedAcc[0].BillingState, addr.State_Province__c);
    System.assertEquals(
      insertedAcc[0].BillingPostalCode,
      addr.Zip_Postal_Code__c
    );
    System.assertEquals(insertedAcc[0].BillingCountry, addr.Country__c);
    System.assertEquals(insertedAcc[0].ShippingCity, addr.City__c);
    System.assertEquals(insertedAcc[0].ShippingState, addr.State_Province__c);
    System.assertEquals(
      insertedAcc[0].ShippingPostalCode,
      addr.Zip_Postal_Code__c
    );
    System.assertEquals(insertedAcc[0].ShippingCountry, addr.Country__c);
  }
  /**
   * @description Method to test if OOTB address fields on bulk accounts are updated correctly
   * @author Aakanksha Sharma | 28/01/2020
   * @return testMethod
   **/
  public static testMethod void updateAddressFields_BulkifiedTest() {
    List<Account> accList = TestDataFactory.createAccounts(
      TestDataFactory.BULK_TEST_RECORD_COUNT,
      true
    );
    List<Address__c> addrList = new List<Address__c>();
    Map<Id, Id> accAddrMap = new Map<Id, Id>();
    List<Account> accToUpdate = new List<Account>();

    for (Account acc : accList) {
      Address__c addr = TestDataFactory.createAccountAddresses(
        acc.ID,
        1,
        false
      )[0];
      addrList.add(addr);
    }

    insert addrList;

    for (Address__c addr : [SELECT Id, Account__c FROM Address__c]) {
      accAddrMap.put(addr.Account__c, addr.Id);
    }
    Test.startTest();
    for (Account acc : accList) {
      acc.Primary_Bill_To__c = accAddrMap.get(acc.Id);
      acc.Primary_Ship_To__c = accAddrMap.get(acc.Id);
      accToUpdate.add(acc);
    }
    update accToUpdate;
    Test.stopTest();
    System.assertEquals(
      TestDataFactory.BULK_TEST_RECORD_COUNT,
      [
        SELECT COUNT()
        FROM Account
        WHERE ShippingCountry != null AND BillingCountry != null
      ]
    );
  }
}