force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Bill_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Billing Address for Account</description>
    <label>Primary Bill-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account.</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Bill-To)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Ship_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Shipping Address for Account</description>
    <label>Primary Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Ship-To)</relationshipLabel>
    <relationshipName>Shipping_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>RUBX-1672: This object will be used to maintain various addresses related to an account</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>RUBX-1672 : This field is used to capture City of the address</description>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-1672 : This field is used to capture Country for Address</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>RUBX-1672 : This field is used to capture State or Province name for the address</description>
    <label>State/Province</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <description>RUBX-1672 : This field is used to capture Street Name for the address</description>
    <label>Street Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>RUBX-1672 : This field is used to capture Postal Code for the address</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerHandler.cls
/**
 * @File Name          : AccountTriggerHandler.cls
 * @Description        : Trigger Handler Class for Account object
 * @Author             : Aakanksha Sharma
 * @Group              : 
 * @Last Modified By   : Aakanksha Sharma
 * @Last Modified On   : 28/01/2020, 12:12:15
 * @Modification Log   : 
 * Ver       Date            Author                 Modification
 * 1.0    27/01/2020   Aakanksha Sharma     Initial Version
**/
public with sharing class AccountTriggerHandler extends TriggerHandler  {
    protected override void beforeUpdate() {
        List<Account> newAcc = (List<Account>) Trigger.new;
        Map<Id, Account> oldAccMap = (Map<Id, Account>) Trigger.oldMap;
        updateAddressFields(newAcc, oldAccMap);       
    }
    /**
    * @description RUBX-1672 : This method update OOTB Billing and Shipping Address fields
    * @author Aakanksha Sharma | 28/01/2020 
    * @param accList 
    * @param oldAccMap 
    * @return void 
    **/
    private void updateAddressFields(
        List<Account> accList,
        Map<Id, Account> oldAccMap
    ) {
        Set<ID> address_Ids = new Set<Id>();
        List<Account> accToUpdate = new List<Account>();
        for (Account acc : accList) {
            Account oldAcc = oldAccMap.get(acc.Id);
            if (( acc.Primary_Bill_To__c != oldAcc.Primary_Bill_To__c) || 
                ( acc.Primary_Ship_To__c != oldAcc.Primary_Ship_To__c)
                )
                {
                    address_Ids.add(acc.Primary_Bill_To__c);
                    address_Ids.add(acc.Primary_Ship_To__c);
                    accToUpdate.add(acc);
                }       
        }
        Map<Id, Address__c> addInfoMap = new Map<Id, Address__c>(
        [
        SELECT ID, City__c, Country__c, State_Province__c, Street_Name__c, Zip_Postal_Code__c
        FROM Address__c
        WHERE id IN :address_Ids
        ]);
        
        for(Account acc : accToUpdate)
        {
            Account oldAcc = oldAccMap.get(acc.Id);
            if (acc.Primary_Bill_To__c != null && acc.Primary_Bill_To__c != oldAcc.Primary_Bill_To__c){
                Address__c addr = addInfoMap.get(acc.Primary_Bill_To__c);
                acc.BillingStreet = addr.Street_Name__c;
                acc.BillingCity = addr.City__c;
                acc.BillingState = addr.State_Province__c;
                acc.BillingPostalCode = addr.Zip_Postal_Code__c;
                acc.BillingCountry = addr.Country__c;
            }
            else if(acc.Primary_Bill_To__c == null)
            {
                acc.BillingStreet = null;
                acc.BillingCity = null;
                acc.BillingState = null;
                acc.BillingPostalCode = null;
                acc.BillingCountry = null;              
            }
            if (acc.Primary_Ship_To__c != null && acc.Primary_Ship_To__c != oldAcc.Primary_Ship_To__c){
                Address__c addr = addInfoMap.get(acc.Primary_Ship_To__c);
                acc.ShippingStreet = addr.Street_Name__c;
                acc.ShippingCity = addr.City__c;
                acc.ShippingState = addr.State_Province__c;
                acc.ShippingPostalCode = addr.Zip_Postal_Code__c;
                acc.ShippingCountry = addr.Country__c;
            }
            else if(acc.Primary_Ship_To__c == null)
            {
                acc.ShippingStreet = null;
                acc.ShippingCity = null;
                acc.ShippingState = null;
                acc.ShippingPostalCode = null;
                acc.ShippingCountry = null;             
            }
            
        }
        
    }
    
}