force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Bill_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Billing Address for Account</description>
    <label>Primary Bill-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account.</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Bill-To)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Ship_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Shipping Address for Account</description>
    <label>Primary Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Ship-To)</relationshipLabel>
    <relationshipName>Shipping_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>RUBX-1672: This object will be used to maintain various addresses related to an account</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : This field is used to associate an Account with Address Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>RUBX-1672 : This field is used to capture City of the address</description>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>RUBX-1672 : This field is used to capture Country for Address</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>RUBX-1672 : This field is used to capture State or Province name for the address</description>
    <label>State/Province</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <description>RUBX-1672 : This field is used to capture Street Name for the address</description>
    <label>Street Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>RUBX-1672 : This field is used to capture Postal Code for the address</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AddressTriggerHandler.cls
/**
 * @File Name          : AddressTriggerHandler.cls
 * @Description        : Handler class for Address Trigger
 * @Author             : Aakanksha Sharma
 * @Group              :
 * @Last Modified By   : Aakanksha Sharma
 * @Last Modified On   : 31/01/2020, 12:30:48
 * @Modification Log   :
 * Ver       Date            Author                 Modification
 * 1.0    31/01/2020   Aakanksha Sharma     Initial Version
 **/
public with sharing class AddressTriggerHandler extends TriggerHandler {
  protected override void afterUpdate() {
    Map<Id, Address__c> newAddrMap = (Map<Id, Address__c>) Trigger.newMap;
    Map<Id, Address__c> oldAddrMap = (Map<Id, Address__c>) Trigger.oldMap;
    updatePrimaryAccounts(newAddrMap, oldAddrMap);
  }
  /**
   * @description RUBX-3978 : When Address is modified, it should update OOTB address fields on Account where it is marked as primary
   * @author Aakanksha Sharma | 31/01/2020
   * @param newAddrMap
   * @param oldAddrMap
   * @return void
   **/
  private void updatePrimaryAccounts(
    Map<Id, Address__c> newAddrMap,
    Map<Id, Address__c> oldAddrMap
  ) {
    Set<Id> addrIds = new Set<Id>();
    List<Account> updatedAccounts = new List<Account>();
    for (Address__c addr : newAddrMap.values()) {
      Address__c oldAddr = oldAddrMap.get(addr.Id);
      if (
        (addr.City__c != oldAddr.City__c ||
        addr.State_Province__c != oldAddr.State_Province__c ||
        addr.Street_Name__c != oldAddr.Street_Name__c ||
        addr.Zip_Postal_Code__c != oldAddr.Zip_Postal_Code__c ||
        addr.Country__c != oldAddr.Country__c) && addr.Account__c != null
      ) {
        addrIds.add(addr.Id);
      }
    }
    if (!addrIds.isEmpty()) {
      List<Account> affectedAccounts = new List<Account>(
        [
          SELECT
            Id,
            BillingStreet,
            BillingCity,
            BillingState,
            BillingPostalCode,
            BillingCountry,
            Primary_Bill_To__c,
            ShippingStreet,
            ShippingCity,
            ShippingState,
            ShippingPostalCode,
            ShippingCountry,
            Primary_Ship_To__c
          FROM Account
          WHERE Primary_Bill_To__c IN :addrIds OR Primary_Ship_To__c IN :addrIds
        ]
      );
      if (!affectedAccounts.isEmpty()) {
        for (Account acc : affectedAccounts) {
          if (
            acc.Primary_Bill_To__c == acc.Primary_Ship_To__c &&
            newAddrMap.containsKey(acc.Primary_Bill_To__c)
          ) {
            Address__c newAddr = newAddrMap.get(acc.Primary_Bill_To__c);
            acc.BillingStreet = newAddr.Street_Name__c;
            acc.BillingCity = newAddr.City__c;
            acc.BillingState = newAddr.State_Province__c;
            acc.BillingPostalCode = newAddr.Zip_Postal_Code__c;
            acc.BillingCountry = newAddr.Country__c;
            acc.ShippingStreet = newAddr.Street_Name__c;
            acc.ShippingCity = newAddr.City__c;
            acc.ShippingState = newAddr.State_Province__c;
            acc.ShippingPostalCode = newAddr.Zip_Postal_Code__c;
            acc.ShippingCountry = newAddr.Country__c;
            updatedAccounts.add(acc);
          } else if (acc.Primary_Bill_To__c != acc.Primary_Ship_To__c) {
            if (
              newAddrMap.containsKey(acc.Primary_Bill_To__c) &&
              !newAddrMap.containsKey(acc.Primary_Ship_To__c)
            ) {
              Address__c newAddr = newAddrMap.get(acc.Primary_Bill_To__c);
              acc.BillingStreet = newAddr.Street_Name__c;
              acc.BillingCity = newAddr.City__c;
              acc.BillingState = newAddr.State_Province__c;
              acc.BillingPostalCode = newAddr.Zip_Postal_Code__c;
              acc.BillingCountry = newAddr.Country__c;
              updatedAccounts.add(acc);
            } else if (
              !newAddrMap.containsKey(acc.Primary_Bill_To__c) &&
              newAddrMap.containsKey(acc.Primary_Ship_To__c)
            ) {
              Address__c newAddr = newAddrMap.get(acc.Primary_Ship_To__c);
              acc.ShippingStreet = newAddr.Street_Name__c;
              acc.ShippingCity = newAddr.City__c;
              acc.ShippingState = newAddr.State_Province__c;
              acc.ShippingPostalCode = newAddr.Zip_Postal_Code__c;
              acc.ShippingCountry = newAddr.Country__c;
              updatedAccounts.add(acc);
            } else if (
              newAddrMap.containsKey(acc.Primary_Bill_To__c) &&
              newAddrMap.containsKey(acc.Primary_Ship_To__c)
            ) {
              Address__c newBillAddr = newAddrMap.get(acc.Primary_Bill_To__c);
              Address__c newShipAddr = newAddrMap.get(acc.Primary_Ship_To__c);
              acc.ShippingStreet = newShipAddr.Street_Name__c;
              acc.ShippingCity = newShipAddr.City__c;
              acc.ShippingState = newShipAddr.State_Province__c;
              acc.ShippingPostalCode = newShipAddr.Zip_Postal_Code__c;
              acc.ShippingCountry = newShipAddr.Country__c;
              acc.BillingStreet = newBillAddr.Street_Name__c;
              acc.BillingCity = newBillAddr.City__c;
              acc.BillingState = newBillAddr.State_Province__c;
              acc.BillingPostalCode = newBillAddr.Zip_Postal_Code__c;
              acc.BillingCountry = newBillAddr.Country__c;
              updatedAccounts.add(acc);
            }
          }
        }

        Database.update(updatedAccounts, true);
      }
    }
  }
}