force-app/main/default/objects/Account/fields/Primary_Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Bill_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Billing Address for Account</description>
    <label>Primary Bill-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account.</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Bill-To)</relationshipLabel>
    <relationshipName>Billing_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Primary_Ship_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : Lookup to capture Primary Shipping Address for Account</description>
    <label>Primary Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select an address record associated with this Account</errorMessage>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>Address__c.Account__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Accounts (Primary Ship-To)</relationshipLabel>
    <relationshipName>Shipping_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>RUBX-1672: This object will be used to maintain various addresses related to an account</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>RUBX-1672 : This field is used to associate an Account with Address Record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street_Name__c.field-meta.xml
<CustomField>
    <fullName>Street_Name__c</fullName>
    <description>RUBX-1672 : This field is used to capture Street Name for the address</description>
    <label>Street Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AddressTriggerHandler_Test.cls
/**
 * @File Name          : AddressTriggerHandler_Test.cls
 * @Description        : Test class for all Address Trigger Handler methods
 * @Author             : Aakanksha Sharma
 * @Group              :
 * @Last Modified By   : Aakanksha Sharma
 * @Last Modified On   : 31/01/2020, 13:26:50
 * @Modification Log   :
 * Ver       Date            Author      		    Modification
 * 1.0    28/01/2020   Aakanksha Sharma     Initial Version
 **/
@istest
public with sharing class AddressTriggerHandler_Test {
  public static final String TEST_STREET = 'Test Street';
  /**
   * @description Account OOTB Billing and Shipping fields should get updated
   * @author Aakanksha Sharma | 31/01/2020
   * @return testMethod
   **/
  public static testMethod void updatePrimaryAccounts_PositiveSingleTest1() {
    Account acc = TestDataFactory.createAccounts(1, true)[0];
    Address__c addr = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    acc.Primary_Bill_To__c = addr.id;
    acc.Primary_Ship_To__c = addr.id;
    update acc;
    // Perform test
    Test.startTest();
    addr.Street_Name__c = TEST_STREET;
    update addr;
    Test.stopTest();

    List<Account> updatedAcc = new List<Account>(
      [SELECT id, BillingStreet, ShippingStreet FROM Account WHERE id = :acc.id]
    );

    System.assertEquals(TEST_STREET, updatedAcc[0].ShippingStreet);
    System.assertEquals(TEST_STREET, updatedAcc[0].BillingStreet);
  }

  /**
   * @description Account OOTB Billing fields should get updated
   * @author Aakanksha Sharma | 31/01/2020
   * @return testMethod
   **/
  public static testMethod void updatePrimaryAccounts_PositiveSingleTest2() {
    Account acc = TestDataFactory.createAccounts(1, true)[0];
    Address__c addr = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    Address__c addr1 = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    acc.Primary_Bill_To__c = addr.id;
    acc.Primary_Ship_To__c = addr1.id;
    update acc;
    // Perform test
    Test.startTest();
    addr.Street_Name__c = TEST_STREET;
    update addr;
    Test.stopTest();

    List<Account> updatedAcc = new List<Account>(
      [SELECT id, BillingStreet, ShippingStreet FROM Account WHERE id = :acc.id]
    );

    System.assertEquals(addr1.Street_Name__c, updatedAcc[0].ShippingStreet);
    System.assertEquals(TEST_STREET, updatedAcc[0].BillingStreet);
  }
  /**
   * @description Account OOTB Shipping fields should get updated
   * @author Aakanksha Sharma | 31/01/2020
   * @return testMethod
   **/
  public static testMethod void updatePrimaryAccounts_PositiveSingleTest3() {
    Account acc = TestDataFactory.createAccounts(1, true)[0];
    Address__c addr = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    Address__c addr1 = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    acc.Primary_Bill_To__c = addr.id;
    acc.Primary_Ship_To__c = addr1.id;
    update acc;
    // Perform test
    Test.startTest();
    addr1.Street_Name__c = TEST_STREET;
    update addr1;
    Test.stopTest();

    List<Account> updatedAcc = new List<Account>(
      [SELECT id, BillingStreet, ShippingStreet FROM Account WHERE id = :acc.id]
    );

    System.assertEquals(addr.Street_Name__c, updatedAcc[0].BillingStreet);
    System.assertEquals(TEST_STREET, updatedAcc[0].ShippingStreet);
  }

  /**
   * @description Account OOTB Billing and Shipping fields should get updated
   * @author Aakanksha Sharma | 31/01/2020
   * @return testMethod
   **/
  public static testMethod void updatePrimaryAccounts_PositiveSingleTest4() {
    Account acc = TestDataFactory.createAccounts(1, true)[0];
    Address__c addr = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    Address__c addr1 = TestDataFactory.createAccountAddresses(
      acc.ID,
      1,
      true
    )[0];
    acc.Primary_Bill_To__c = addr.id;
    acc.Primary_Ship_To__c = addr1.id;
    update acc;
    List<Address__c> addrList = new List<Address__c>();
    // Perform test
    Test.startTest();
    addr1.Street_Name__c = TEST_STREET;
    addrList.add(addr1);
    addr.Street_Name__c = TEST_STREET;
    addrList.add(addr);
    update addrList;
    Test.stopTest();

    List<Account> updatedAcc = new List<Account>(
      [SELECT id, BillingStreet, ShippingStreet FROM Account WHERE id = :acc.id]
    );

    System.assertEquals(TEST_STREET, updatedAcc[0].BillingStreet);
    System.assertEquals(TEST_STREET, updatedAcc[0].ShippingStreet);
  }
  /**
   * @description Method to test if OOTB address fields on bulk accounts are updated correctly, on updating Bulk Addresses
   * @author Aakanksha Sharma | 28/01/2020
   * @return testMethod
   **/
  public static testMethod void updatePrimaryAccounts_BulkifiedTest() {
    List<Account> accList = TestDataFactory.createAccounts(
      TestDataFactory.BULK_TEST_RECORD_COUNT,
      true
    );
    List<Address__c> addrList = new List<Address__c>();
    Map<Id, Id> accAddrMap = new Map<Id, Id>();
    List<Account> accToUpdate = new List<Account>();
    List<Address__c> addrToUpdate = new List<Address__c>();
    for (Account acc : accList) {
      Address__c addr = TestDataFactory.createAccountAddresses(
        acc.ID,
        1,
        false
      )[0];
      addrList.add(addr);
    }

    insert addrList;

    for (Address__c addr : [SELECT Id, Account__c FROM Address__c]) {
      accAddrMap.put(addr.Account__c, addr.Id);
    }
    for (Account acc : accList) {
      acc.Primary_Bill_To__c = accAddrMap.get(acc.Id);
      acc.Primary_Ship_To__c = accAddrMap.get(acc.Id);
      accToUpdate.add(acc);
    }
    update accToUpdate;
    Test.startTest();
    for (Address__c addr : addrList) {
      addr.Street_Name__c = TEST_STREET;
      addrToUpdate.add(addr);
    }
    update addrToUpdate;
    Test.stopTest();
    System.assertEquals(
      TestDataFactory.BULK_TEST_RECORD_COUNT,
      [
        SELECT COUNT()
        FROM Account
        WHERE ShippingStreet = :TEST_STREET AND BillingStreet = :TEST_STREET
      ]
    );
  }
}