force-app/main/default/objects/Opportunity/fields/MainProduct__c.field-meta.xml
<CustomField>
    <fullName>MainProduct__c</fullName>
    <description>used in Licence Compliance process to identify for which particular product the audit was done. Oliver 17/07/12</description>
    <label>Main Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Main_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pricing_Country__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Country__c</fullName>
    <description>RUBX-453 : Field to capture pricing country</description>
    <label>Pricing Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>British Virgin Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Brunei</fullName>
    </customValue>
    <description>RUBX-594 : Used to determine Region for Partner Accounts</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Main_Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Almonde</fullName>
    </customValue>
    <customValue>
        <fullName>ARIS</fullName>
    </customValue>
    <customValue>
        <fullName>Bankmaster</fullName>
    </customValue>
    <customValue>
        <fullName>Carbon Trading</fullName>
    </customValue>
    <customValue>
        <fullName>Cashier</fullName>
    </customValue>
    <customValue>
        <fullName>Cash Portal</fullName>
    </customValue>
    <customValue>
        <fullName>CLX</fullName>
    </customValue>
    <customValue>
        <fullName>CMS</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmation Matching Services</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Risk Vantage</fullName>
    </customValue>
    <customValue>
        <fullName>Credit Quest</fullName>
    </customValue>
    <customValue>
        <fullName>Digiwave</fullName>
    </customValue>
    <customValue>
        <fullName>Eagleye</fullName>
    </customValue>
    <customValue>
        <fullName>FB Cash Management</fullName>
    </customValue>
    <customValue>
        <fullName>FB Corporate Channels</fullName>
    </customValue>
    <customValue>
        <fullName>FB Credit Management Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>FB CrowdLending</fullName>
    </customValue>
    <customValue>
        <fullName>FB Equation</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Digital Sales</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Gameo</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence IPD</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Islamic</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Loan Origination</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Mobile PFM</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Online</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Party Management</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence PFM</fullName>
    </customValue>
    <customValue>
        <fullName>FB Essence Single Customer View</fullName>
    </customValue>
    <masterLabel>Main Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreatePSChangeRequestBtnRedirectCtrl.cls
public class CreatePSChangeRequestBtnRedirectCtrl
{	
	Opportunity oppty;
	
	public CreatePSChangeRequestBtnRedirectCtrl()
	{
		string opptyId = ApexPages.currentPage().getParameters().get('id');
		Opportunity[] results = [
			select
				Id,
				Name,
				AccountId,
				Sales_Region_FY07__c,
				CurrencyIsoCode,
				Type,
				MainProduct__c,
				Pricing_Country__c ,
				IsWon
			from Opportunity
			where Id = :opptyId
		];
		if (results != null && results.size() == 1) {
			oppty = results[0];
		} 
	}
	
	public PageReference RedirectUser()
	{
		if (oppty != null) {
			return oppty.IsWon ? getCreatePSCRPage() : getSorryPage();
		}
		return null;
	}
	
	private PageReference getCreatePSCRPage()
	{
		PageReference pr = new PageReference('/006/e');
		pr.getParameters().put('retURL', '/' + oppty.Id);
		pr.getParameters().put('accid', oppty.AccountId);
		pr.getParameters().put(
			'RecordType',
			GenericServices.getRecordTypesNameMapBySObject('Opportunity').get(Constants.OPPORTUNITY_RECORD_TYPE_CHANGE_ORDER).id
		);
		pr.getParameters().put('ent', 'Opportunity');
		pr.getParameters().put('opp3', oppty.Name + '-' + 'change request name');
		pr.getParameters().put('00N20000000ohBZ', oppty.Sales_Region_FY07__c);
		pr.getParameters().put('currcode', oppty.CurrencyIsoCode);
		pr.getParameters().put('opp5', oppty.Type);
		pr.getParameters().put('00N20000003e4pH', '"FALSE"');
		pr.getParameters().put('00N20000000h1Ck', oppty.MainProduct__c);
		pr.getParameters().put('00N20000003e4ok', '"Services Only"');
		pr.getParameters().put('CF00N20000003e4ol', oppty.Name);
		pr.getParameters().put('00N20000003eTbS', oppty.Pricing_Country__c);
		return pr;
	}
	
	private PageReference getSorryPage()
	{
		return Page.CROportunitySorryneedsclosedwon;
	}
}