force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>AAE_Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__ApprovedBy__c.field-meta.xml
<CustomField>
        <fullName>sbaa__ApprovedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who approved this Approval</description>
        <inlineHelpText>User who approved this Approval</inlineHelpText>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ApprovedApprovals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Approver associated with this Approval.</description>
        <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>sbaa__Approver__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__AssignedGroupId__c.field-meta.xml
<CustomField>
        <fullName>sbaa__AssignedGroupId__c</fullName>
        <description>ID of the Group the Approval is assigned to, if applicable</description>
        <inlineHelpText>ID of the Group the Approval is assigned to, if applicable</inlineHelpText>
        <label>Assigned Group Id</label>
        <length>18</length>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__AssignedTo__c.field-meta.xml
<CustomField>
        <fullName>sbaa__AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the User to which the Approval is assigned</description>
        <inlineHelpText>Lookup to the User to which the Approval is assigned</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Status__c.field-meta.xml
<CustomField>
        <fullName>sbaa__Status__c</fullName>
        <description>Status of this approval.</description>
        <inlineHelpText>Status of this approval.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ItemsToApproveController.cls
public class ItemsToApproveController{

    public List<SBAA__Approval__c> requestedApprovals {get;set;}
    public List<ApprovalListItemWrapper> approvalLists {get;set;}

    public List<ProcessInstanceWorkItem> processInstanceItems {get;set;}
    
    public Integer approvalListSize {get;set;}
  
    
    public ItemsToApproveController(){

        getApprovalListItemWrapperItems();
    }
    
    public List<ApprovalListItemWrapper> getApprovalListItemWrapperItems(){

        Set<Id> instanceIds = new Set<Id>();
        Map<Id, ProcessInstanceStep> mapProcessInstanceStep = new Map<Id, ProcessInstanceStep>();
        Map<Id, String> mapApprovals = new Map<Id, String>();
        String createdDateValue;
        String lastActorInfo;
        approvalLists = new List<ApprovalListItemWrapper>();
        approvalListSize=0;
        
        Set<Id> userIds = new Set<Id>{UserInfo.getUserId()};

        List<Group> groupList = getGroups(userIds);

        //System.debug('groupList ---->' + groupList);
        //System.debug('userIds ---->' + userIds);
         
        for(Id userId : userIds){

          for(Group groupRecord : groupList){

            if(groupRecord.groupMembers != null &&  groupRecord.groupMembers.size() > 0){
                
                for(GroupMember member : groupRecord.groupMembers){
                    userIds.add(member.Id);
                }

            }else if (groupRecord.relatedId  == UserInfo.getUserRoleId()){
                userIds.add(groupRecord.relatedId);
            }
          }
        }
        
        requestedApprovals = getRequestedApprovals(userIds);
        List<SBAA__Approval__c> approvedApprovals = getApprovedApprovals();

//get standard approvals                                                                                     
        processInstanceItems = getProcessInstanceWorkItem(userIds);
        
        for(ProcessInstanceWorkItem processItem: processInstanceItems){
            instanceIds.add(processItem.ProcessInstance.Id);
        }
        
        List<ProcessInstanceStep> processInstanceSteps = getProcessInstanceSteps(instanceIds);
                                            

        for(ProcessInstanceStep processStep: processInstanceSteps){
            
            if(!mapProcessInstanceStep.containsKey(processStep.ProcessInstance.Id)){
                mapProcessInstanceStep.put(processStep.ProcessInstance.Id, processStep);
            }
        }
        
        for(ProcessInstanceWorkItem processItem: processInstanceItems){

            ProcessInstanceStep processStep = mapProcessInstanceStep.get(processItem.ProcessInstance.Id);
            lastActorInfo = processStep != null ? processItem.Actor.Name : '';
            createdDateValue = processItem.CreatedDate.format('MM/dd/yyyy hh:mm a');

            approvalLists.add(new ApprovalListItemWrapper(processItem.ProcessInstance.TargetObjectId,
                            processItem.ProcessInstance.TargetObject.Name,
                            processItem.ProcessInstance.TargetObject.Type.substringBefore('_'),
                            lastActorInfo, processItem.Id,true,createdDateValue));
        }
    
//get Advanced Approvals

    //get approved approvals to populate last actor info - if approval is in a chain
        for(SBAA__Approval__c currentApproval: approvedApprovals){

            if(!mapApprovals.containsKey(currentApproval.Quote__c)){

               mapApprovals.put(currentApproval.Quote__c, currentApproval.SBAA__ApprovedBy__r.Name);
            }
        }

    //get requested approvals to display
        for(SBAA__Approval__c currentApproval: requestedApprovals)
        {
            lastActorInfo = mapApprovals.get(currentApproval.Quote__c) != null ? mapApprovals.get(currentApproval.Quote__c) : ' ';
            createdDateValue = currentApproval.CreatedDate.format('MM/dd/yyyy hh:mm a');

            approvalLists.add(new ApprovalListItemWrapper(currentApproval.Quote__c, currentApproval.Quote__r.Name,
                                                        'Quote', lastActorInfo, currentApproval.Id, false, createdDateValue));
        }
        
        approvalListSize = approvalLists.size();
        return approvalLists;
    }


//query helper methods 

    public List<Group> getGroups(Set<Id> userIds){

        List<Group> groupList = [
            SELECT Id, Type, RelatedId,
                (SELECT Id, UserOrGroupId
                FROM GroupMembers 
                WHERE Id IN : userIds) 
            FROM Group
        ]; 

        return groupList;
    } 

    public List<SBAA__Approval__c> getRequestedApprovals(Set<Id> userIds){

        List<SBAA__Approval__c> requestedApprovals = [
            SELECT Id,SBAA__Approver__c, Quote__c,Quote__r.Name,
                    SBAA__Approver__r.Name,CreatedDate
            FROM SBAA__Approval__c 
            WHERE (SBAA__AssignedTo__c IN :userIds OR SBAA__AssignedGroupId__c IN :userIds) 
            AND SBAA__Status__c = 'Requested'
        ];
        
        return requestedApprovals;
    }

    public List<SBAA__Approval__c> getApprovedApprovals(){

        List<SBAA__Approval__c> approvedApprovals = [
            SELECT Id, SBAA__ApprovedBy__r.Name, Quote__c 
            FROM SBAA__Approval__c 
            WHERE SBAA__Status__c = 'Approved' 
            ORDER BY LastModifiedDate ASC
        ];

        return approvedApprovals;
    }

    public List<ProcessInstanceStep> getProcessInstanceSteps(Set<Id> instanceIds){

        List<ProcessInstanceStep> processInstanceSteps = [
            SELECT Id,ActorId,Actor.Name, ProcessInstance.Id 
            FROM ProcessInstanceStep
            WHERE (StepStatus = 'Approved' OR StepStatus = 'Started')
            AND ProcessInstance.Id in : instanceIds
            ORDER BY CreatedDate DESC
        ];

        return processInstanceSteps;
    }

    public List<ProcessInstanceWorkItem> getProcessInstanceWorkItem(Set<Id> userIds){

        List<ProcessInstanceWorkItem> workItems = [
            SELECT Id, ActorId, ElapsedTimeInDays, ProcessInstanceId, Actor.Name,
                ProcessInstance.TargetObjectId,
                ProcessInstance.TargetObject.Name,
                ProcessInstance.TargetObject.Type,
                ProcessInstance.LastActorId, OriginalActorId,
                ProcessInstance.LastActor.Name,CreatedDate,
                OriginalActor.Name, ProcessInstance.Status 
            FROM ProcessInstanceWorkItem
            WHERE ActorId IN :userIds
            AND ProcessInstance.Status = 'Pending'
            ORDER BY CreatedDate DESC
        ];

        return workItems;
    }
    

//Approval List Items Wrapper Class
    public class ApprovalListItemWrapper
    {
        public string relatedTo {get;set;}
        public string objectType {get;set;}
        public string mostRecentApprover {get;set;}
        public string targetObjectId {get;set;}
        public boolean isStandard {get;set;}
        public string processId {get;set;}
        public string dateSubmitted {get;set;}
        
        public ApprovalListItemWrapper(String objId, String objRelatedTo, String objType, String recentApprover, String processId, Boolean objIsStandard, String dateSubmitted)
        {
            this.isStandard = objIsStandard;
            this.targetObjectId = objId;
            this.relatedTo = objRelatedTo;
            this.objectType = objType;
            this.mostRecentApprover= recentApprover; 
            this.processId = processId;
            this.dateSubmitted = dateSubmitted;
            
        }
    }
}