force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>AAE_Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </CustomField>

force-app/main/default/classes/PreviewApprovalsOverrideController.cls
/**
* @File Name          : PreviewApprovalsOverrideController.cls
* @Description        : Overrride of the standard Preview Approvals page from Advanced Approvals
* @Author             : Dan Meseroll
* @Group              : ATG
* @Last Modified By   : Dan Meseroll
* @Last Modified On   : 1/22/2020, 12:00:00 PM
* @Modification Log   : 
* Ver       Date            Author      		    Modification        JIRA Ticket
* 1.0       1/22/2020       Dan Meseroll            Initial Version     RUBX-107
**/
public with sharing class PreviewApprovalsOverrideController {
    
    private SBQQ__Quote__c sbQuote;
    
    public SBAA__Approval__c[] approvals {
        get {
            if (approvals == null) {
                approvals = SBAA.ApprovalAPI.preview(sbQuote.Id, SBAA__Approval__c.Quote__c);
            }
            return approvals;
        } 
        set;
    }
    
    public PreviewApprovalsOverrideController(ApexPages.StandardController stdController) {
        if(!Test.isRunningTest()) {
            stdController.addFields(new List<String> {'SBQQ__Primary__c'});
        }
        this.sbQuote = (SBQQ__Quote__c)stdController.getRecord();
    }

    public PageReference onSubmit() {
        if (sbQuote != null) {
            //Don't allow non-Primary quotes to be submitted for Approval.
            if ((sbQuote.SBQQ__Primary__c == null) || (sbQuote.SBQQ__Primary__c == false)) {
                ApexPages.Message message = new ApexPages.Message(ApexPages.Severity.WARNING, System.Label.Only_Primary_Quotes);
                ApexPages.addMessage(message);
                return null;
            }
            SBAA.ApprovalAPI.submit(sbQuote.Id, SBAA__Approval__c.Quote__c);
        }
        
        PageReference pr = new PageReference('/' + sbQuote.Id);
        pr.setRedirect(true);
        return pr;
    }

    public PageReference onCancel() {
        PageReference pr = new PageReference('/' + sbQuote.Id);
        pr.setRedirect(true);
        return pr;
    }
}