force-app/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>AAE_Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__ApprovalStep__c.field-meta.xml
<CustomField>
        <fullName>sbaa__ApprovalStep__c</fullName>
        <description>Step (level) at which this approval is required.</description>
        <inlineHelpText>Step (level) at which this approval is required.</inlineHelpText>
        <label>Approval Step</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Approver associated with this Approval.</description>
        <inlineHelpText>Lookup to the Approver associated with this Approval.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>sbaa__Approver__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__AssignedTo__c.field-meta.xml
<CustomField>
        <fullName>sbaa__AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the User to which the Approval is assigned</description>
        <inlineHelpText>Lookup to the User to which the Approval is assigned</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__RecordField__c.field-meta.xml
<CustomField>
        <fullName>sbaa__RecordField__c</fullName>
        <description>API Name of the Approval field looking up to the record being approved</description>
        <inlineHelpText>API Name of the Approval field looking up to the record being approved</inlineHelpText>
        <label>Record Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Rule__c.field-meta.xml
<CustomField>
        <fullName>sbaa__Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approval rule that generated this approval.</description>
        <inlineHelpText>Approval rule that generated this approval.</inlineHelpText>
        <label>Rule</label>
        <referenceTo>sbaa__ApprovalRule__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Status__c.field-meta.xml
<CustomField>
        <fullName>sbaa__Status__c</fullName>
        <description>Status of this approval.</description>
        <inlineHelpText>Status of this approval.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/sbaa__ApprovalRule__c/sbaa__ApprovalRule__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalRuleHelp</customHelpPage>
    <description>This is the Rule associated with an Approval.</description>
    <label>Approval Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__ApprovalRule__c/fields/sbaa__ApprovalStep__c.field-meta.xml
<CustomField>
        <fullName>sbaa__ApprovalStep__c</fullName>
        <description>Step at which this Approval Rule is evaluated</description>
        <inlineHelpText>Step at which this Approval Rule is evaluated</inlineHelpText>
        <label>Approval Step</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </CustomField>

force-app/main/default/objects/sbaa__ApprovalRule__c/fields/sbaa__Approver__c.field-meta.xml
<CustomField>
        <fullName>sbaa__Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approver associated with this Approval Rule.</description>
        <inlineHelpText>Approver associated with this Approval Rule.</inlineHelpText>
        <label>Approver</label>
        <referenceTo>sbaa__Approver__c</referenceTo>
        <relationshipLabel>Approval Rules</relationshipLabel>
        <relationshipName>ApprovalRules</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/sbaa__ApprovalRule__c/fields/sbaa__TargetObject__c.field-meta.xml
<CustomField>
        <fullName>sbaa__TargetObject__c</fullName>
        <description>API Name of the object to which this Rule applies</description>
        <inlineHelpText>API Name of the object to which this Rule applies</inlineHelpText>
        <label>Target Object</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>SBQQ__Quote__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </CustomField>

force-app/main/default/objects/sbaa__Approver__c/sbaa__Approver__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApproverHelp</customHelpPage>
    <description>Approvers are associated with the Approval Rule, driving what occurs on the Approval itself.</description>
    <label>Approver</label>
    <nameField>
        <label>Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approvers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sbaa__Approver__c/fields/sbaa__User__c.field-meta.xml
<CustomField>
        <fullName>sbaa__User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If Approver is a single User, lookup to that User</description>
        <inlineHelpText>If Approver is a single User, lookup to that User</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Approvers</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Account__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__EndDate__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
        <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Product__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__StartDate__c.field-meta.xml
<CustomField>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </CustomField>

force-app/main/default/classes/ItemsToApproveControllerTest.cls
@isTest
private class ItemsToApproveControllerTest
{
    @isTest static void testDataInit()
    {
    	
    	Profile testProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        User testUser = new User(Alias = 'test',
        						Email='testUser1@test.com', 
            					EmailEncodingKey='UTF-8',
            					LastName='TestLastName',
            					LanguageLocaleKey='en_US',
            					LocaleSidKey='en_US',
            					ProfileId = testProfile.Id,
            					TimeZoneSidKey='America/Los_Angeles',
            					UserName='userEmail4306@test.com');
        insert testUser;

        //add user to a group
        Group testGroup = new Group(Name = 'testGroup');
        insert testGroup;

        GroupMember testMember = new GroupMember(GroupId = testGroup.Id, UserOrGroupId = testUser.Id);
        insert testMember;


        System.runAs(testUser)
        {
            
            Product2 testProduct = new Product2(Name='Test Product');    
            insert testProduct;

            //Id pricebookId = Test.getStandardPricebookId();
            //insert pricebookId;
             
            Account testAccount = new Account(name='Test CPQAccount', BillingState = 'MT', BillingCountry = 'US');
            insert testAccount;
            
            Contact testContact = new Contact(FirstName = 'Test First Name',
            									LastName='Test Last Name',
            									AccountId = testAccount.Id);
            insert testContact;
            
            Opportunity testOppty = new Opportunity(AccountId = testAccount.Id, 
            										Name ='Test CPQOpp', StageName='Open',
            										CloseDate = Date.today().addMonths(12));
            insert testOppty;
            
            SBQQ__Quote__c testQuote = new SBQQ__Quote__c(SBQQ__Account__c = testAccount.Id,
            										SBQQ__Opportunity2__c = testOppty.Id,
            										SBQQ__StartDate__c = Date.today(),
            										SBQQ__EndDate__c = Date.today().addMonths(12));
            insert testQuote;

            SBQQ__Quote__c testQuote2 = new SBQQ__Quote__c(SBQQ__Account__c = testAccount.Id,
            										SBQQ__Opportunity2__c = testOppty.Id,
            										SBQQ__StartDate__c = Date.today(),
            										SBQQ__EndDate__c = Date.today().addMonths(12));
            insert testQuote2;

            
            SBQQ__QuoteLine__c testQuoteLine = new SBQQ__QuoteLine__c(SBQQ__StartDate__c = Date.today(),
            														SBQQ__EndDate__c = Date.today().addMonths(12),
            														SBQQ__Product__c = testProduct.Id,														
            														SBQQ__Quote__c = testQuote.Id);
            insert testQuoteLine;
            
            SBAA__ApprovalRule__c testApprovalRuleQuote = new SBAA__ApprovalRule__c(Name='Test Approval Rule',
            																	SBAA__TargetObject__c = 'SBQQ__Quote__c');
            insert testApprovalRuleQuote;

            
            SBAA__Approver__c testApprover = new SBAA__Approver__c(Name = UserInfo.getUserName(),
            														SBAA__User__c = UserInfo.getUserId());
            insert testApprover;
            
            SBAA__Approval__c testQuoteApproval = new SBAA__Approval__c(SBAA__Status__c = 'Requested',
            														SBAA__RecordField__c = 'Quote__c',
            														SBAA__ApprovalStep__c = 10,
            														SBAA__Rule__c = testApprovalRuleQuote.Id,
            														SBAA__AssignedTo__c = UserInfo.getUserId(),
            														Quote__c = testQuote.Id );

            insert testQuoteApproval;

            SBAA__Approval__c testQuoteApproval2 = new SBAA__Approval__c(SBAA__Status__c = 'Approved',
            														SBAA__RecordField__c = 'Quote__c',
            														SBAA__ApprovalStep__c = 10,
            														SBAA__Rule__c = testApprovalRuleQuote.Id,
            														SBAA__AssignedTo__c = UserInfo.getUserId(),
            														Quote__c = testQuote2.Id );

          	insert testQuoteApproval2;

			//Approval.ProcessSubmitRequest submitApproval = new Approval.ProcessSubmitRequest();
			//	submitApproval.setObjectId(testQuote2.id);
			//	submitApproval.setSubmitterId(testUser.Id);
			//	Approval.ProcessResult result = Approval.process(submitApproval);
          
             
            Test.startTest();
            ItemsToApproveController testController = new ItemsToApproveController(); 
            //System.assert(result.isSuccess());
            Test.stopTest();
        }
    }
}